title: "Marilyn Ponzón | IA aplicada a Salud"
description: "Consultoría en inteligencia artificial y análisis de datos clínicos."
baseurl: "" # Déjalo vacío si es un sitio principal
url: "https://marypoza76.github.io"
permalink: pretty
theme: jekyll-theme-architect
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
